name: dcload-serial PR check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dcload-serial
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull the Toolchain Image
      run: docker pull ghcr.io/kallistiosunchained/dc-kos-toolchain:latest

    - name: Build dcload-serial
      run: |
        docker run --rm -v $(pwd):/workspace ghcr.io/kallistiosunchained/dc-kos-toolchain:latest \
        /bin/bash -c "cd /workspace && make"
